### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by Juliauru** [aigora/twE100-twe100_biblio#2]
Hola, por favor, ¿me podéis decir si debo borrar el otro grupo con el mismo nombre? Además, Óscar no está en el grupo de E100 así que puede tener problemas con la evaluación. 
Si no sabéis arreglarlo venid a vernos o contactad con nosotros.

**Comment by danielrodriguezescudero** [comment]
Hola, no se cual es el otro grupo con el mismo nombre, no lo veo. ¿Oscario20 no es orcar torija?

**Comment by Juliauru** [comment]
Había otro grupo en el que solo estaba  Óscar, lo he eliminado.  De todas formas Óscar está metido en este equipo pero no en el del E100. Que venga a vernos y le metemmos.
